baseURL = "https://new.docs.toot.app/"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
title = "Mastodon documentation"
pygmentsCodeFences = true
pygmentsStyle = "dracula"
metaDataFormat = "yaml"
paginate = 100
enableGitInfo = true

[menu]
  [[menu.docs]]
    name = "Mastodonの使い方"
    weight = 10
    identifier = "user"
    url = "/user/"
  [[menu.docs]]
    name = "Mastodonの構築"
    weight = 20
    identifier = "admin"
    url = "/admin/"
  [[menu.docs]]
    name = "アプリケーションの開発"
    weight = 30
    identifier = "client"
    url = "/client/"
  [[menu.docs]]
    name = "コントリビューション"
    weight = 40
    identifier = "dev"
    url = "/dev/"
  [[menu.docs]]
    name = "スペック"
    weight = 50
    identifier = "spec"
    url = "/spec/"
  [[menu.docs]]
    name = "REST API"
    weight = 60
    identifier = "api"
    url = "/api/"
  [[menu.docs]]
    name = "API一覧"
    weight = 70
    identifier = "methods"
    url = "/methods/"
  [[menu.docs]]
    name = "APIエンティティ"
    weight = 80
    identifier = "entities"
    url = "/entities/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = -99
    [languages.en.menu]
      [[languages.en.menu.docs]]
        name = "Using Mastodon"
        weight = 10
        identifier = "user"
        url = "/user/"
      [[languages.en.menu.docs]]
        name = "Running Mastodon"
        weight = 20
        identifier = "admin"
        url = "/admin/"
      [[languages.en.menu.docs]]
        name = "Developing Mastodon apps"
        weight = 30
        identifier = "client"
        url = "/client/"
      [[languages.en.menu.docs]]
        name = "Contributing to Mastodon"
        weight = 40
        identifier = "dev"
        url = "/dev/"
      [[languages.en.menu.docs]]
        name = "Spec compliance"
        weight = 50
        identifier = "spec"
        url = "/spec/"
      [[languages.en.menu.docs]]
        name = "REST API"
        weight = 60
        identifier = "api"
        url = "/api/"
      [[languages.en.menu.docs]]
        name = "API Methods"
        weight = 70
        identifier = "methods"
        url = "/methods/"
      [[languages.en.menu.docs]]
        name = "API Entities"
        weight = 80
        identifier = "entities"
        url = "/entities/"

  [languages.ja]
    contentDir = "content/ja"
    languageName = "日本語"
    weight = -99
